
configs:
  secret:
    # argocd4all
    argocdServerAdminPassword: '$2a$10$9UU1ieLSxTgw9TBU.2ATfey0BQwggeQCQtPTf4ESlK2b/K/AvunfK'

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - argocd.localtest.me
