
configs:
  secret:
    # argocd4all
    argocdServerAdminPassword: '$2a$10$9UU1ieLSxTgw9TBU.2ATfey0BQwggeQCQtPTf4ESlK2b/K/AvunfK'

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - argocd.localtest.me
    # https: true
    # tls:
    # - hosts:
    #     - argocd.localtest.me
    #   secretName: argocd-local-cert-file

