
primary:
  initdb:
    scriptsSecret: postgres-init

  persistence:
    enabled: true
    existingClaim: postgres
    mountPath: /bitnami/postgresql
    subPath: ""

# volumePermissions:
#   enabled: true 


  
